USE Money_Manager;
CREATE TABLE USER_DETAILS (USER_ID INT PRIMARY KEY,USER_NAME VARCHAR(20) NOT NULL,
EMAIL VARCHAR(20),USER_PASSWORD VARCHAR(20) NOT NULL UNIQUE,CREATED_DATE DATETIME,MODIFIED_DATE DATETIME)


CREATE TABLE ACCOUNT( USER_ID INT,
					  ACCOUNT_NUMBER INT NOT NULL, 
					  NAME VARCHAR(30) NOT NULL, 
					  BANK VARCHAR(50) NOT NULL,
					  BALANCE INT NOT NULL,
					  ACCOUNT_TYPE VARCHAR(50) NOT NULL,
					  CREATED_DATE DATETIME,
					  MODIFIED_DATE DATETIME,
					  FOREIGN KEY(USER_ID) REFERENCES USER_DETAILS(USER_ID))

SELECT * FROM USER_DETAILS

--INSERT DETAILS 
ALTER PROCEDURE SP_GET_USER_DETAILS (@USER_ID INT,@USER_NAME VARCHAR(20),@EMAIL VARCHAR(20),
									@PASSWORD_ VARCHAR(10),@CREATED_DATE DATETIME=NULL,@MODIFIED_DATE DATETIME=NULL)
AS
SET @CREATED_DATE=COALESCE(@CREATED_DATE,GETDATE())
SET @MODIFIED_DATE=COALESCE(@MODIFIED_DATE,GETDATE())
BEGIN
	INSERT INTO USER_DETAILS (USER_ID,USER_NAME,EMAIL,PASSWORD_,CREATED_DATE,MODIFIED_DATE)
	VALUES(@USER_ID,@USER_NAME,@EMAIL,@PASSWORD_,@CREATED_DATE,@MODIFIED_DATE)
END
EXEC SP_GET_USER_DETAILS 111,'HELLO','WANDERER@GMAIL.COM','WANDERER@18'
EXEC SP_GET_USER_DETAILS 112,'WORLD','HODOPHILE@GMAIL.COM','HODOPHILE@18'

SELECT * FROM USER_DETAILS

--SEE PARTICULAR DETAILS
CREATE PROCEDURE SP_GET_PTCL_USER_DETAILS (@USER_NAME VARCHAR(20))
AS
BEGIN
	SELECT * FROM USER_DETAILS WHERE USER_NAME=@USER_NAME
END
EXEC SP_GET_PTCL_USER_DETAILS 'WORLD'

--SEE ALL DETAILS
ALTER PROCEDURE SP_GET_ALL_USER_DETAILS
AS
BEGIN
	SELECT * FROM USER_DETAILS
END
EXEC SP_GET_ALL_USER_DETAILS

--UPDATE PASSWORD
ALTER PROCEDURE SP_UPDATE_PASS_ON_USER_DETAILS(@USER_NAME VARCHAR(20), @PASSWORD_ VARCHAR(10))
AS
BEGIN
	UPDATE USER_DETAILS SET PASSWORD_=@PASSWORD_ WHERE USER_NAME=@USER_NAME
END
EXEC SP_UPDATE_PASS_ON_USER_DETAILS 'WORLD','HODPHILE$@18'

SELECT * FROM USER_DETAILS



------------DATA LOAD FROM FROM ETL-------------




