SELECT* INTO EMP_TRG_FF_SAMPLE FROM EMP WHERE 1=2;

SELECT * FROM EMP_TRG_FF_SAMPLE

SELECT * FROM DEPT
SELECT EMPNO,ENAME,JOB,SAL,DEPTNO,ENAME AS DNAME,ENAME AS LOC INTO TRG_JOIN FROM EMP WHERE 1=2;
SELECT * FROM TRG_JOIN

SELECT * INTO TRG_JOIN2 FROM EMP WHERE 1=2
SELECT * FROM TRG_JOIN2	
SELECT * FROM EMP


SELECT * FROM TRG_JOIN2_REJ

SELECT * FROM TRG_OUTER_JOIN

SELECT EMPNO,ENAME,SAL,DEPTNO  INTO FROM EMP WHERE DEPTNO==30 OR DEPTN0=20

SELECT * FROM TRG_DIFF_STRUCT_20

SELECT * INTO TRG_UNION FROM EMP WHERE 1=2

SELECT * FROM TRG_UNION
SELECT * INTO TRG_UNION_ALL FROM EMP WHERE 1=2;
SELECT * FROM TRG_UNION_ALL

SELECT DEPTNO,SAL INTO TRG_AGGR_EMP FROM EMP WHERE 1=2

SELECT * FROM TRG_AGGR_EMP

SELECT * FROM EMP
SELECT EMPNO,ENAME,SAL,DEPTNO,COMM,JOB,SAL AS TSAL,SAL AS TRATE,SAL AS TAX,SAL AS NETSAL INTO TRG_DAY2_T1_TB1 FROM EMP WHERE 1=2
SELECT EMPNO,ENAME,SAL,DEPTNO,COMM,JOB,SAL AS TSAL,SAL AS TRATE,SAL AS TAX,SAL AS NETSAL INTO TRG_DAY2_T1_TB2 FROM EMP WHERE 1=2

SELECT * FROM TRG_DAY2_T1_TB1

SELECT EMPNO,ENAME,SAL,COMM,DEPTNO INTO TRG_DAY2_T2_TB1 FROM EMP WHERE 1=2
SELECT DEPTNO,JOB,COMM INTO TRG_DAY2_T2_TB2 FROM EMP WHERE 1=2

SELECT * FROM TRG_DAY2_T2_TB1
SELECT * FROM TRG_DAY2_T2_TB2

SELECT * FROM EMP


SELECT EMPNO,ENAME,SAL,DEPTNO,ENAME AS DNAME,ENAME AS LOC INTO TRG_DAY2_T3_TB1 FROM EMP WHERE 1=2

SELECT EMPNO,ENAME,SAL,DEPTNO,COMM,JOB INTO TRG_DAY2_T4_TB1 FROM EMP WHERE 1=2
SELECT EMPNO,ENAME,SAL,DEPTNO,COMM,JOB INTO TRG_DAY2_T4_TB2 FROM EMP WHERE 1=2
SELECT EMPNO,ENAME,SAL,DEPTNO,COMM,JOB INTO TRG_DAY2_T4_TB3 FROM EMP WHERE 1=2
SELECT EMPNO,ENAME,SAL,DEPTNO,COMM,JOB INTO TRG_DAY2_T4_TB4 FROM EMP WHERE 1=2
SELECT EMPNO,ENAME,SAL,DEPTNO,COMM,JOB INTO TRG_DAY2_T4_TB5 FROM EMP WHERE 1=2

	SELECT * FROM TRG_DAY2_T4_TB1
	SELECT * FROM TRG_DAY2_T4_TB2
	SELECT * FROM TRG_DAY2_T4_TB3
	SELECT * FROM TRG_DAY2_T4_TB4
	SELECT * FROM TRG_DAY2_T4_TB5

SELECT EMPNO,ENAME,SAL,DEPTNO,COMM,JOB INTO TRG_DAY2_T5_TB1 FROM EMP WHERE 1=2
SELECT EMPNO,ENAME,SAL,COMM,SAL AS TSAL,DEPTNO,JOB,ENAME AS DNAME,ENAME AS LOC INTO TRG_DAY2_T5_TB1 FROM EMP WHERE 1=2

use Prasath_DB

SELECT * FROM TRG_DAY2_T5_TB1
SELECT * FROM TRG_DAY2_T5_TB2
SELECT * FROM TRG_DAY2_T4_TB5

SELECT DEPTNO,ENAME AS DNAME,ENAME AS LOC,SAL AS SUM_SAL,SAL AS MAX_SAL,SAL AS TAX_SUM_SAL INTO TRG_DAY2_T6_TB1 FROM EMP WHERE 1=2
SELECT * FROM TRG_DAY2_T6_TB1