SELECT * FROM EMP

SELECT * FROM TRG_EMP


SELECT EMPNO as E_NO,ENAME,JOB,DEPTNO AS DEPT_NO INTO TRG_DIFF_STRUCT_1 FROM EMP WHERE 1=2;
SELECT * FROM TRG_DIFF_STRUCT_1

SELECT EMPNO,ENAME,JOB,DEPTNO INTO TRG_DIFF_STRUCT_10 FROM EMP WHERE 1=2;
SELECT EMPNO,ENAME,JOB,SAL,DEPTNO INTO TRG_DIFF_STRUCT_20 FROM EMP WHERE 1=2;

SELECT * FROM TRG_DIFF_STRUCT_10
SELECT * FROM TRG_DIFF_STRUCT_20

SELECT * FROM TRG_DIFF_STRUCT_FILTER

SELECT * FROM TRG_DIFF_STRUCT_10_MAIN
SELECT * FROM TRG_DIFF_STRUCT_FILTER_REMAIN


SELECT * FROM DEPT

SELECT * INTO TRG_DEPT FROM DEPT WHERE 1=2;

SELECT * FROM TRG_DEPT


SELECT EMPNO,ENAME,SAL,DEPTNO INTO EMP_T2 FROM EMP WHERE 1=2; 
SELECT * FROM EMP_T2

SELECT EMPNO,ENAME,SAL,DEPTNO,JOB INTO EMP_T3 FROM EMP WHERE 1=2; 
SELECT * FROM EMP_T3

SELECT * FROM EMP

SELECT EMPNO,ENAME,SAL,DEPTNO,JOB INTO EMP_T4 FROM EMP WHERE 1=2; 
SELECT * FROM EMP_T4

use Prasath_DB
SELECT* FROM EMP_T4_TB1
SELECT* FROM EMP_T4_TB2
SELECT* FROM EMP_T4_TB3


SELECT* FROM EMP_T5_TB1
SELECT* FROM EMP_T5_TB2
SELECT* FROM EMP_T5_TB3


SELECT EMPNO,ENAME,SAL,SAL AS TAX,DEPTNO INTO EMP_T6 FROM EMP WHERE 1=2; 
SELECT * FROM EMP_T6
SELECT * FROM EMP WHERE DEPTNO=10 ORDER BY DEPTNO;
SELECT * FROM EMP


SELECT * FROM EMP_T7

SELECT EMPNO,ENAME,SAL,COMM,SAL AS TSAL,SAL AS TAX,DEPTNO INTO EMP_T8 FROM EMP WHERE 1=2;
SELECT * FROM EMP_T8
SELECT * FROM EMP_T8_TB2
