SELECT * FROM EMP

SELECT * INTO EMP_SAMPLE FROM EMP WHERE 1=2

ALTER TABLE EMP_SAMPLE ADD SKEY INT,VERSION_NO INT,START_DATE_ DATE,END_DATE DATE
ALTER TABLE EMP_SAMPLE ADD FLAG INT

SELECT * FROM EMP_SAMPLE
SELECT * INTO EMP_COPY FROM EMP 

UPDATE EMP_COPY SET SAL=1500 WHERE EMPNO=7934
UPDATE EMP_COPY SET SAL=2000 WHERE EMPNO=7934