Prasath_DB;

CREATE TABLE USER_DETAILS (USER_ID INT PRIMARY KEY,USER_NAME VARCHAR(20) NOT NULL,
EMAIL VARCHAR(20),USER_PASSWORD VARCHAR(20) NOT NULL UNIQUE,CREATED_DATE DATETIME,MODIFIED_DATE DATETIME)

SELECT * FROM USER_DETAILS;

ALTER TABLE USER_DETAILS ALTER COLUMN EMAIL VARCHAR(100);